[auth_db]
url = "sqlite:////var/lib/alarick_mail/auth.db"
#url = "mysql+pymysql://user:password@host:port/database"
#url = "postgresql://user:password@host:port/database"

[quota]
quota = true
default = 1024
unit = "MB" # B, KB, MB, GB

[smtp]
queue_dir = "/var/lib/alarick_mail"
cert_file = "/etc/letsencrypt/live/mail.example.org/fullchain.pem"
key_file = "/etc/letsencrypt/live/mail.example.org/privkey.pem"

[smtp.incoming]
bind = "0.0.0.0"
port = 25
tls = "starttls"
require_tls = false
#filters = ["/path/to/filter/spam_filter.py"]

[smtp.submission]
bind = "0.0.0.0"
port = 587
tls = "starttls"
require_tls = true
filters = ["/path/to/filter/quota.py"]